// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: history.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'History';

export interface SaveVideoInHistoryDto {
  userId: string;
  videoId: string;
}

export interface RemoveVideoFromHistoryDto {
  userId: string;
  videoId: string;
}

export interface RemoveAllVideosFromHistoryDto {
  userId: string;
}

export interface VideoSavedInHistoryResponse {
  saved: boolean;
  response: string;
}

export interface VideoRemovedInHistoryResponse {
  removed: boolean;
  response: string;
}

export interface AllVideoRemovedFromHistoryResponse {
  cleared: boolean;
  response: string;
}

export const HISTORY_PACKAGE_NAME = 'History';

export interface HistoryServiceClient {
  addVideoInHistory(request: SaveVideoInHistoryDto): Observable<VideoSavedInHistoryResponse>;

  removeVideoFromHistory(
    request: RemoveVideoFromHistoryDto,
  ): Observable<VideoRemovedInHistoryResponse>;

  clearHistory(
    request: RemoveAllVideosFromHistoryDto,
  ): Observable<AllVideoRemovedFromHistoryResponse>;
}

export interface HistoryServiceController {
  addVideoInHistory(
    request: SaveVideoInHistoryDto,
  ):
    | Promise<VideoSavedInHistoryResponse>
    | Observable<VideoSavedInHistoryResponse>
    | VideoSavedInHistoryResponse;

  removeVideoFromHistory(
    request: RemoveVideoFromHistoryDto,
  ):
    | Promise<VideoRemovedInHistoryResponse>
    | Observable<VideoRemovedInHistoryResponse>
    | VideoRemovedInHistoryResponse;

  clearHistory(
    request: RemoveAllVideosFromHistoryDto,
  ):
    | Promise<AllVideoRemovedFromHistoryResponse>
    | Observable<AllVideoRemovedFromHistoryResponse>
    | AllVideoRemovedFromHistoryResponse;
}

export function HistoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['addVideoInHistory', 'removeVideoFromHistory', 'clearHistory'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('HistoryService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('HistoryService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const HISTORY_SERVICE_NAME = 'HistoryService';
