export enum DomainVideoState {
  DRAFT = 'DRAFT',
  PENDING_UPLOAD = 'PENDING_UPLOAD',
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  TRANSCODING = 'TRANSCODING',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
}
