// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: reaction.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Reaction';

export enum ReactionType {
  REACTION_LIKE = 0,
  REACTION_UNLIKE = 1,
  REACTION_DISLIKE = 2,
  REACTION_UNDISLIKE = 3,
  UNRECOGNIZED = -1,
}

export interface VideoReactionDto {
  userId: string;
  videoId: string;
  reaction: ReactionType;
}

export interface ReactedOnVideoDto {
  videoId: string;
  userId: string;
}

export interface ReactionLikeCountVideoDto {
  videoId: string;
}

export interface ReactionDislikeCountVideoDto {
  videoId: string;
}

export interface ReactionResponse {
  response: string;
}

export interface ReactionFoundForVideoResponse {
  id: string;
  userId: string;
  videoId: string;
  reaction: ReactionType;
}

export interface Empty {}

export interface ReactionHealthCheckRequest {
  service: string;
}

export interface ReactionLikeCountVideoResponse {
  likes: number;
}

export interface ReactionDislikeCountVideoResponse {
  dislikes: number;
}

export interface ReactionHealthCheckResponse {
  status: ReactionHealthCheckResponse_ServingStatus;
}

export enum ReactionHealthCheckResponse_ServingStatus {
  UNKNOWN = 0,
  SERVING = 1,
  NOT_SERVING = 2,
  SERVICE_UNKNOWN = 3,
  UNRECOGNIZED = -1,
}

export const REACTION_PACKAGE_NAME = 'Reaction';

export interface ReactionServiceClient {
  reactToVideo(request: VideoReactionDto): Observable<ReactionResponse>;

  getLikesCountForVideo(
    request: ReactionLikeCountVideoDto,
  ): Observable<ReactionLikeCountVideoResponse>;

  getDislikesCountForVideo(
    request: ReactionDislikeCountVideoDto,
  ): Observable<ReactionDislikeCountVideoResponse>;

  findReactionOfUserOnVideo(request: ReactedOnVideoDto): Observable<ReactionFoundForVideoResponse>;

  check(request: ReactionHealthCheckRequest): Observable<ReactionHealthCheckResponse>;
}

export interface ReactionServiceController {
  reactToVideo(
    request: VideoReactionDto,
  ): Promise<ReactionResponse> | Observable<ReactionResponse> | ReactionResponse;

  getLikesCountForVideo(
    request: ReactionLikeCountVideoDto,
  ):
    | Promise<ReactionLikeCountVideoResponse>
    | Observable<ReactionLikeCountVideoResponse>
    | ReactionLikeCountVideoResponse;

  getDislikesCountForVideo(
    request: ReactionDislikeCountVideoDto,
  ):
    | Promise<ReactionDislikeCountVideoResponse>
    | Observable<ReactionDislikeCountVideoResponse>
    | ReactionDislikeCountVideoResponse;

  findReactionOfUserOnVideo(
    request: ReactedOnVideoDto,
  ):
    | Promise<ReactionFoundForVideoResponse>
    | Observable<ReactionFoundForVideoResponse>
    | ReactionFoundForVideoResponse;

  check(
    request: ReactionHealthCheckRequest,
  ):
    | Promise<ReactionHealthCheckResponse>
    | Observable<ReactionHealthCheckResponse>
    | ReactionHealthCheckResponse;
}

export function ReactionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'reactToVideo',
      'getLikesCountForVideo',
      'getDislikesCountForVideo',
      'findReactionOfUserOnVideo',
      'check',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ReactionService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ReactionService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const REACTION_SERVICE_NAME = 'ReactionService';
