// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: subscribe.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Subscribe';

export interface SubscribeMessage {
  userId: string;
  channelId: string;
}

export interface UnSubscribeMessage {
  userId: string;
  channelId: string;
}

export interface SubscribedResponse {
  subscribed: boolean;
  response: string;
}

export const SUBSCRIBE_PACKAGE_NAME = 'Subscribe';

export interface SubscribeServiceClient {
  subscribe(request: SubscribeMessage): Observable<SubscribedResponse>;

  unSubscribe(request: UnSubscribeMessage): Observable<SubscribedResponse>;
}

export interface SubscribeServiceController {
  subscribe(
    request: SubscribeMessage,
  ): Promise<SubscribedResponse> | Observable<SubscribedResponse> | SubscribedResponse;

  unSubscribe(
    request: UnSubscribeMessage,
  ): Promise<SubscribedResponse> | Observable<SubscribedResponse> | SubscribedResponse;
}

export function SubscribeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['subscribe', 'unSubscribe'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('SubscribeService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('SubscribeService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const SUBSCRIBE_SERVICE_NAME = 'SubscribeService';
