services:
  analytics-database:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - analytics_data:/var/lib/clickhouse
      - analytics_logs:/var/log/clickhouse-server
    networks:
      - analytics-database-network

  #-------------------------------------------------------------------------------------------------------------#
  #                                          METRICS AND OBSERVABILITY                                          #
  #-------------------------------------------------------------------------------------------------------------#

  prom-server:
    image: prom/prometheus
    container_name: prom-server
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    networks:
      - observer
      - services
    deploy:
      resources:
        reservations:
          memory: "256M"
          cpus: "0.5"
        limits:
          memory: "512M"
          cpus: "1"
    logging: &logging
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      gateway:
        condition: service_healthy
      users:
        condition: service_healthy
      channel:
        condition: service_healthy
      videos:
        condition: service_healthy
      video-transcoder:
        condition: service_healthy
      reaction:
        condition: service_healthy
      views:
        condition: service_healthy
      comments:
        condition: service_healthy
      email:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 5555:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - observer
      - services
    deploy:
      resources:
        reservations:
          memory: "256M"
          cpus: "0.5"
        limits:
          memory: "512M"
          cpus: "1"
    logging: *logging

  grafana-loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - observer
      - services
    user: root
    deploy:
      resources:
        reservations:
          memory: "256M"
          cpus: "0.5"
        limits:
          memory: "512M"
          cpus: "0.5"
    logging: *logging

  #-------------------------------------------------------------------------------------------------------------#
  #                                              AUTHORIZATION                                                  #
  #-------------------------------------------------------------------------------------------------------------#

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    networks:
      - authorization
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          memory: "256M"
          cpus: "0.25"
        limits:
          memory: "512M"
          cpus: "0.5"
    logging: *logging

  migrate:
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    networks:
      - authorization
    deploy:
      resources:
        reservations:
          memory: "256M"
          cpus: "0.25"
        limits:
          memory: "512M"
          cpus: "0.5"
    logging: *logging
    depends_on:
      postgres:
        condition: service_healthy

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3333:3000"
    networks:
      - authorization
    deploy:
      resources:
        reservations:
          memory: "256M"
          cpus: "0.25"
        limits:
          memory: "512M"
          cpus: "0.5"
    logging: *logging
    depends_on:
      migrate:
        condition: service_completed_successfully

  #-------------------------------------------------------------------------------------------------------------#
  #                                              MICROSERVICES                                                  #
  #-------------------------------------------------------------------------------------------------------------#

  gateway:
    image: mytube/gateway/production:latest
    container_name: gateway
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    env_file:
      - apps/api-gateway/.env
    ports:
      - 3000:3000
    networks:
      - services
      - authorization
      - observer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m
    deploy: &service_resources
      resources:
        reservations:
          cpus: "0.25"
          memory: "256M"
        limits:
          cpus: "0.25"
          memory: "512M"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      users:
        condition: service_healthy
      channel:
        condition: service_healthy
      videos:
        condition: service_healthy
      video-transcoder:
        condition: service_healthy
      views:
        condition: service_healthy
      reaction:
        condition: service_healthy
      comments:
        condition: service_healthy
      email:
        condition: service_healthy

  users:
    image: mytube/users/production:latest
    container_name: users
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    env_file:
      - apps/users/.env
    networks:
      - services
      - observer
    healthcheck: &grpc-healthcheck
      test: ["CMD", "grpc_health_probe", "-addr=:5000"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 180s
    deploy: *service_resources
    depends_on:
      users-migrate:
        condition: service_completed_successfully
      email:
        condition: service_healthy

  authz:
    image: mytube/authz/production:latest
    container_name: authz
    build:
      context: .
      dockerfile: apps/authz/Dockerfile
    env_file:
      - apps/authz/.env
    networks:
      - services
      - observer
      - authorization
    deploy: *service_resources
    healthcheck: *grpc-healthcheck

  users-migrate:
    image: mytube/users/production:latest
    container_name: users-database-migrate
    env_file:
      - apps/users/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]
    restart: "no"

  channel:
    image: mytube/channel/production:latest
    container_name: channel
    build:
      context: .
      dockerfile: apps/channel/Dockerfile
    env_file:
      - apps/channel/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    deploy: *service_resources
    healthcheck: *grpc-healthcheck
    depends_on:
      channel-migrate:
        condition: service_completed_successfully
      email:
        condition: service_healthy

  channel-migrate:
    image: mytube/channel/production:latest
    container_name: channel-database-migrate
    build:
      context: .
      dockerfile: apps/channel/Dockerfile
    env_file:
      - apps/channel/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  videos:
    image: mytube/videos/production:latest
    container_name: videos
    build:
      context: .
      dockerfile: apps/videos/Dockerfile
    env_file:
      - apps/videos/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources
    depends_on:
      videos-migrate:
        condition: service_completed_successfully
      email:
        condition: service_healthy

  videos-migrate:
    image: mytube/videos/production:latest
    container_name: videos-database-migrate
    env_file:
      - apps/videos/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  video-transcoder:
    image: mytube/video-transcoder/production:latest
    container_name: video-transcoder
    build:
      context: .
      dockerfile: apps/video-transcoder/Dockerfile
    env_file:
      - apps/video-transcoder/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - transcoder-volume:/home/node/transcoded-videos
    networks:
      - services
      - observer
    healthcheck: &message-broker-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 180s
    deploy: *service_resources
    depends_on:
      videos:
        condition: service_healthy

  views:
    image: mytube/views/production:latest
    container_name: views
    build:
      context: .
      dockerfile: apps/views/Dockerfile
    env_file:
      - apps/views/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources
    depends_on:
      views-migrate:
        condition: service_completed_successfully

  views-migrate:
    image: mytube/views/production:latest
    container_name: views-migrate
    env_file:
      - apps/views/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  reaction:
    image: mytube/reaction/production:latest
    container_name: reaction
    build:
      context: .
      dockerfile: apps/reaction/Dockerfile
    env_file:
      - apps/reaction/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources

  comments:
    image: mytube/comments/production:latest
    container_name: comments
    build:
      context: .
      dockerfile: apps/comments/Dockerfile
    env_file:
      - apps/comments/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources
    depends_on:
      comments-migrate:
        condition: service_completed_successfully

  comments-migrate:
    image: mytube/comments/production:latest
    container_name: comments-database-migrate
    env_file:
      - apps/comments/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  playlist:
    image: mytube/playlist/production:latest
    container_name: playlist
    build:
      context: .
      dockerfile: apps/playlist/Dockerfile
    env_file:
      - apps/playlist/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources
    depends_on:
      playlist-migrate:
        condition: service_completed_successfully

  playlist-migrate:
    image: mytube/playlist/production:latest
    container_name: playlist-database-migrate
    env_file:
      - apps/playlist/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  subscribe:
    image: mytube/subscribe/production:latest
    container_name: subscribe
    build:
      context: .
      dockerfile: apps/subscribe/Dockerfile
    env_file:
      - apps/subscribe/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources
    depends_on:
      subscribe-migrate:
        condition: service_completed_successfully

  subscribe-migrate:
    image: mytube/subscribe/production:latest
    container_name: subscribe-database-migrate
    env_file:
      - apps/subscribe/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  history:
    image: mytube/history/production:latest
    container_name: history
    build:
      context: .
      dockerfile: apps/history/Dockerfile
    env_file:
      - apps/history/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources
    depends_on:
      history-migrate:
        condition: service_completed_successfully

  history-migrate:
    image: mytube/history/production:latest
    container_name: history-database-migrate
    env_file:
      - apps/history/.env
    networks:
      - services
      - observer
    entrypoint:
      ["npx", "prisma", "migrate", "deploy", "--schema", "prisma/schema.prisma"]

  email:
    image: mytube/email/production:latest
    container_name: email
    build:
      context: .
      dockerfile: apps/email/Dockerfile
    env_file:
      - apps/email/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *message-broker-healthcheck
    deploy: *service_resources

  projection:
    image: mytube/projection/production:latest
    container_name: projection
    build:
      context: .
      dockerfile: apps/projection/Dockerfile
    env_file:
      - apps/projection/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *message-broker-healthcheck
    deploy: *service_resources

  query:
    image: mytube/query/production:latest
    container_name: query
    build:
      context: .
      dockerfile: apps/query/Dockerfile
    env_file:
      - apps/query/.env
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - services
      - observer
    healthcheck: *grpc-healthcheck
    deploy: *service_resources

#-------------------------------------------------------------------------------------------------------------#
#                                                  VOLUMES                                                    #
#-------------------------------------------------------------------------------------------------------------#

volumes:
  grafana-storage: {}
  transcoder-volume: {}
  analytics_data: {}
  analytics_logs: {}

#-------------------------------------------------------------------------------------------------------------#
#                                                 NETWORKS                                                    #
#-------------------------------------------------------------------------------------------------------------#

networks:
  services: {}
  authorization: {}
  observer: {}
  analytics-database-network: {}
