// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: videos.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Video';

export enum VideoTransportPublishStatus {
  TRANSPORT_PENDING = 0,
  TRANSPORT_PROCESSING = 1,
  TRANSPORT_PROCESSED = 2,
  TRANSPORT_PUBLISHED = 3,
  TRANSPORT_FAILED = 4,
  UNRECOGNIZED = -1,
}

export enum VideoTransportVisibilityStatus {
  TRANSPORT_PRIVATE = 0,
  TRANSPORT_PUBLIC = 1,
  TRANSPORT_UNLISTED = 2,
  UNRECOGNIZED = -1,
}

export enum VideoTransportSortOption {
  TRANSPORT_NEWEST = 0,
  TRANSPORT_OLDEST = 1,
  TRANSPORT_POPULAR = 2,
  UNRECOGNIZED = -1,
}

export interface GetPresignedUrlDto {
  fileName?: string | undefined;
  userId: string;
}

export interface VideoCreateDto {
  ownerId: string;
  channelId: string;
  title: string;
  videoFileIdentifier: string;
  videoThumbnailIdentifier: string;
  categories: string[];
  description?: string | undefined;
  videoTransportPublishStatus: VideoTransportPublishStatus;
  videoTransportVisibilityStatus: VideoTransportVisibilityStatus;
}

export interface VideoFindDto {
  id: string;
}

export interface VideoUpdateDto {
  id: string;
  title?: string | undefined;
  videoFileIdentifier?: string | undefined;
  videoThumbnailIdentifier?: string | undefined;
  categories: string[];
  description?: string | undefined;
  videoTransportPublishStatus?: VideoTransportPublishStatus | undefined;
  videoTransportVisibilityStatus?: VideoTransportVisibilityStatus | undefined;
}

export interface VideoFindQueryDto {
  limit?: number | undefined;
  skip?: number | undefined;
  categories: string[];
  channelId?: string | undefined;
  userId?: string | undefined;
  search?: string | undefined;
  videoTransportSortOption?: VideoTransportSortOption | undefined;
}

export interface GetPreSignedUrlResponse {
  response: string;
  presignedUrl: string;
  fileIdentifier: string;
}

export interface VideoPublishedResponse {
  response: string;
  videoId: string;
}

export interface VideoFoundResponse {
  id: string;
  ownerId: string;
  channelId: string;
  title: string;
  videoFileIdentifier: string;
  videoThumbnailIdentifier: string;
  categories: string[];
  description?: string | undefined;
  videoTransportPublishStatus: VideoTransportPublishStatus;
  videoTransportVisibilityStatus: VideoTransportVisibilityStatus;
}

export interface VideosFoundResponse {
  videoFindDto: VideoFindDto[];
}

export interface VideoUpdatedResponse {
  response: string;
  videoId: string;
}

export interface Empty {}

export interface VideosHealthCheckRequest {
  service: string;
}

export interface VideosHealthCheckResponse {
  status: VideosHealthCheckResponse_ServingStatus;
}

export enum VideosHealthCheckResponse_ServingStatus {
  UNKNOWN = 0,
  SERVING = 1,
  NOT_SERVING = 2,
  SERVICE_UNKNOWN = 3,
  UNRECOGNIZED = -1,
}

export const VIDEO_PACKAGE_NAME = 'Video';

export interface VideoServiceClient {
  getPresignedUrlForVideoFileUpload(
    request: GetPresignedUrlDto,
  ): Observable<GetPreSignedUrlResponse>;

  getPresignedUrlForThumbnailFileUpload(
    request: GetPresignedUrlDto,
  ): Observable<GetPreSignedUrlResponse>;

  save(request: VideoCreateDto): Observable<VideoPublishedResponse>;

  findOne(request: VideoFindDto): Observable<VideoFoundResponse>;

  findAll(request: Empty): Observable<VideosFoundResponse>;

  update(request: VideoUpdateDto): Observable<VideoUpdatedResponse>;

  findVideos(request: VideoFindQueryDto): Observable<VideosFoundResponse>;

  check(request: VideosHealthCheckRequest): Observable<VideosHealthCheckResponse>;
}

export interface VideoServiceController {
  getPresignedUrlForVideoFileUpload(
    request: GetPresignedUrlDto,
  ):
    | Promise<GetPreSignedUrlResponse>
    | Observable<GetPreSignedUrlResponse>
    | GetPreSignedUrlResponse;

  getPresignedUrlForThumbnailFileUpload(
    request: GetPresignedUrlDto,
  ):
    | Promise<GetPreSignedUrlResponse>
    | Observable<GetPreSignedUrlResponse>
    | GetPreSignedUrlResponse;

  save(
    request: VideoCreateDto,
  ): Promise<VideoPublishedResponse> | Observable<VideoPublishedResponse> | VideoPublishedResponse;

  findOne(
    request: VideoFindDto,
  ): Promise<VideoFoundResponse> | Observable<VideoFoundResponse> | VideoFoundResponse;

  findAll(
    request: Empty,
  ): Promise<VideosFoundResponse> | Observable<VideosFoundResponse> | VideosFoundResponse;

  update(
    request: VideoUpdateDto,
  ): Promise<VideoUpdatedResponse> | Observable<VideoUpdatedResponse> | VideoUpdatedResponse;

  findVideos(
    request: VideoFindQueryDto,
  ): Promise<VideosFoundResponse> | Observable<VideosFoundResponse> | VideosFoundResponse;

  check(
    request: VideosHealthCheckRequest,
  ):
    | Promise<VideosHealthCheckResponse>
    | Observable<VideosHealthCheckResponse>
    | VideosHealthCheckResponse;
}

export function VideoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getPresignedUrlForVideoFileUpload',
      'getPresignedUrlForThumbnailFileUpload',
      'save',
      'findOne',
      'findAll',
      'update',
      'findVideos',
      'check',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('VideoService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('VideoService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VIDEO_SERVICE_NAME = 'VideoService';
