// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: authz.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'authZ';

export interface CheckRelationDto {
  user: string;
  relation: string;
  resource: string;
}

export interface CreateRelationDto {
  user: string;
  relation: string;
  resource: string;
}

export interface IsRelatedResponse {
  allowed: boolean;
}

export interface RelationCreatedResponse {
  created: boolean;
}

export const AUTH_Z_PACKAGE_NAME = 'authZ';

export interface AuthZServiceClient {
  checkRelation(request: CheckRelationDto): Observable<IsRelatedResponse>;

  createRelation(request: CreateRelationDto): Observable<RelationCreatedResponse>;
}

export interface AuthZServiceController {
  checkRelation(
    request: CheckRelationDto,
  ): Promise<IsRelatedResponse> | Observable<IsRelatedResponse> | IsRelatedResponse;

  createRelation(
    request: CreateRelationDto,
  ):
    | Promise<RelationCreatedResponse>
    | Observable<RelationCreatedResponse>
    | RelationCreatedResponse;
}

export function AuthZServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['checkRelation', 'createRelation'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('AuthZService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('AuthZService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_Z_SERVICE_NAME = 'AuthZService';
