export enum BUFFER_EXCEPTION {
  BUFFER_CONNECTION_EXCEPTION = 'BUFFER_CONNECTION_EXCEPTION',
  BUFFER_SAVE_EXCEPTION = 'BUFFER_SAVE_EXCEPTION',
  BUFFER_FLUSH_EXCEPTION = 'BUFFER_FLUSH_EXCEPTION',
  BUFFER_TIMEOUT_EXCEPTION = 'BUFFER_TIMEOUT_EXCEPTION',
  BUFFER_UNKNOWN_EXCEPTION = 'BUFFER_UNKNOWN_EXCEPTION',
}
