export enum DATABASE_EXCEPTION {
  DATABASE_CONNECTION_EXCEPTION = 'DATABASE_CONNECTION_EXCEPTION',
  DATABASE_UNKNOWN_EXCEPTION = 'DATABASE_UNKNOWN_EXCEPTION',
  DATABASE_INVALID_QUERY_EXCEPTION = 'DATABASE_INVALID_QUERY_EXCEPTION',
  DATABASE_ENTRY_ALREADY_EXISTS_EXCEPTION = 'DATABASE_ENTRY_ALREADY_EXISTS_EXCEPTION',
  DATABASE_ENTRY_DOES_NOT_EXISTS_EXCEPTION = 'DATABASE_ENTRY_DOES_NOT_EXISTS_EXCEPTION',
}
