export enum MESSAGE_BROKER_EXCEPTION {
  MESSAGE_BROKER_CONNECTION_EXCEPTION = 'MESSAGE_BROKER_CONNECTION_EXCEPTION',
  MESSAGE_BROKER_TIMEOUT_EXCEPTION = 'MESSAGE_BROKER_TIMEOUT_EXCEPTION',
  MESSAGE_BROKER_UNKNOWN_EXCEPTION = 'MESSAGE_BROKER_UNKNOWN_EXCEPTION',
  CACHE_TIMEOUT_EXCEPTION = 'CACHE_TIMEOUT_EXCEPTION',
  CACHE_UNKNOWN_EXCEPTION = 'CACHE_UNKNOWN_EXCEPTION',
}
