// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: playlist.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Playlist';

export interface CreatePlaylistDto {
  userId: string;
  playlistName: string;
}

export interface AddVideoInPlaylist {
  userId: string;
  videoId: string;
  playlistName: string;
}

export interface RemoveVideoFromPlaylist {
  userId: string;
  videoId: string;
  playlistName: string;
}

export interface PlaylistCreatedResponse {
  created: boolean;
  response: string;
}

export interface VideoAddedToPlaylistResponse {
  added: boolean;
  response: string;
}

export interface VideoRemovedFromPlaylistResponse {
  added: boolean;
  response: string;
}

export const PLAYLIST_PACKAGE_NAME = 'Playlist';

export interface PlaylistServiceClient {
  createPlaylist(request: CreatePlaylistDto): Observable<PlaylistCreatedResponse>;

  addVideoToPlaylist(request: AddVideoInPlaylist): Observable<VideoAddedToPlaylistResponse>;

  removeVideoFromPlaylist(
    request: RemoveVideoFromPlaylist,
  ): Observable<VideoRemovedFromPlaylistResponse>;
}

export interface PlaylistServiceController {
  createPlaylist(
    request: CreatePlaylistDto,
  ):
    | Promise<PlaylistCreatedResponse>
    | Observable<PlaylistCreatedResponse>
    | PlaylistCreatedResponse;

  addVideoToPlaylist(
    request: AddVideoInPlaylist,
  ):
    | Promise<VideoAddedToPlaylistResponse>
    | Observable<VideoAddedToPlaylistResponse>
    | VideoAddedToPlaylistResponse;

  removeVideoFromPlaylist(
    request: RemoveVideoFromPlaylist,
  ):
    | Promise<VideoRemovedFromPlaylistResponse>
    | Observable<VideoRemovedFromPlaylistResponse>
    | VideoRemovedFromPlaylistResponse;
}

export function PlaylistServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createPlaylist',
      'addVideoToPlaylist',
      'removeVideoFromPlaylist',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PlaylistService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PlaylistService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const PLAYLIST_SERVICE_NAME = 'PlaylistService';
