// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: reaction.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Reaction';

export enum ReactionType {
  REACTION_LIKE = 0,
  REACTION_UNLIKE = 1,
  REACTION_DISLIKE = 2,
  REACTION_UNDISLIKE = 3,
  UNRECOGNIZED = -1,
}

export interface VideoReactionDto {
  userId: string;
  videoId: string;
  reaction: ReactionType;
}

export interface ReactionResponse {
  response: string;
}

export const REACTION_PACKAGE_NAME = 'Reaction';

export interface ReactionServiceClient {
  reactToVideo(request: VideoReactionDto): Observable<ReactionResponse>;
}

export interface ReactionServiceController {
  reactToVideo(
    request: VideoReactionDto,
  ): Promise<ReactionResponse> | Observable<ReactionResponse> | ReactionResponse;
}

export function ReactionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['reactToVideo'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ReactionService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ReactionService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const REACTION_SERVICE_NAME = 'ReactionService';
