// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: read.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Read';

export interface GetUserProfileFromIdDto {
  userId: string;
}

export interface GetUserProfileFromAuthIdDto {
  userAuthId: string;
}

export interface UserProfileMessage {
  userId: string;
  email: string;
  userAuthId: string;
  avatar: string;
  handle: string;
  phoneNumber?: string | undefined;
  isPhoneNumberVerified?: boolean | undefined;
  dob?: string | undefined;
}

export interface GetChannelFromIdDto {
  channelId: string;
}

export interface GetChannelFromUserIdDto {
  userId: string;
}

export interface ChannelMessage {
  channelId: string;
  userId: string;
  coverImage: string;
  bio: string;
}

export interface GetUserProfileResponse {
  found: boolean;
  user?: UserProfileMessage | undefined;
}

export interface GetChannelResponse {
  found: boolean;
  channel?: ChannelMessage | undefined;
}

export const READ_PACKAGE_NAME = 'Read';

/** QueryService provides read-only query RPCs for retrieving user profiles and channels. */

export interface ReadQueryServiceClient {
  /** GetUserProfileFromId returns the user profile for a given user ID. */

  getUserProfileFromId(request: GetUserProfileFromIdDto): Observable<GetUserProfileResponse>;

  /** GetUserProfileFromAuthId returns the user profile for a given authentication ID. */

  getUserProfileFromAuthId(
    request: GetUserProfileFromAuthIdDto,
  ): Observable<GetUserProfileResponse>;

  /** GetChannelFromId returns the channel for a given channel ID. */

  getChannelFromId(request: GetChannelFromIdDto): Observable<GetChannelResponse>;

  /** GetChannelFromUserId returns the channel associated with a user ID. */

  getChannelFromUserId(request: GetChannelFromUserIdDto): Observable<GetChannelResponse>;
}

/** QueryService provides read-only query RPCs for retrieving user profiles and channels. */

export interface ReadQueryServiceController {
  /** GetUserProfileFromId returns the user profile for a given user ID. */

  getUserProfileFromId(
    request: GetUserProfileFromIdDto,
  ): Promise<GetUserProfileResponse> | Observable<GetUserProfileResponse> | GetUserProfileResponse;

  /** GetUserProfileFromAuthId returns the user profile for a given authentication ID. */

  getUserProfileFromAuthId(
    request: GetUserProfileFromAuthIdDto,
  ): Promise<GetUserProfileResponse> | Observable<GetUserProfileResponse> | GetUserProfileResponse;

  /** GetChannelFromId returns the channel for a given channel ID. */

  getChannelFromId(
    request: GetChannelFromIdDto,
  ): Promise<GetChannelResponse> | Observable<GetChannelResponse> | GetChannelResponse;

  /** GetChannelFromUserId returns the channel associated with a user ID. */

  getChannelFromUserId(
    request: GetChannelFromUserIdDto,
  ): Promise<GetChannelResponse> | Observable<GetChannelResponse> | GetChannelResponse;
}

export function ReadQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getUserProfileFromId',
      'getUserProfileFromAuthId',
      'getChannelFromId',
      'getChannelFromUserId',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ReadQueryService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ReadQueryService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const READ_QUERY_SERVICE_NAME = 'ReadQueryService';
