// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: videos.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Video';

export enum VideoState {
  TRANSPORT_DRAFT = 0,
  TRANSPORT_PENDING_UPLOAD = 1,
  TRANSPORT_UPLOADED = 2,
  TRANSPORT_PROCESSING = 3,
  TRANSPORT_TRANSCODING = 4,
  TRANSPORT_READY_TO_PUBLISH = 5,
  TRANSPORT_PUBLISHED = 6,
  TRANSPORT_FAILED = 7,
  UNRECOGNIZED = -1,
}

export enum VideoVisibilityState {
  TRANSPORT_PRIVATE = 0,
  TRANSPORT_PUBLIC = 1,
  TRANSPORT_UNLISTED = 2,
  UNRECOGNIZED = -1,
}

export enum VideoTransportSortOption {
  TRANSPORT_NEWEST = 0,
  TRANSPORT_OLDEST = 1,
  TRANSPORT_POPULAR = 2,
  UNRECOGNIZED = -1,
}

export interface GetPresignedUrlDto {
  fileName?: string | undefined;
  userId: string;
}

export interface VideoSaveDraftDto {
  userId: string;
  channelId: string;
  title: string;
  categories: string[];
  description?: string | undefined;
}

export interface CheckUploadedVideoDto {
  id: string;
}

export interface VideoUpdateDto {
  id: string;
  title?: string | undefined;
  fileIdentifier?: string | undefined;
  thumbnailIdentifier?: string | undefined;
  categories: string[];
  description?: string | undefined;
  videoVisibilityState?: VideoVisibilityState | undefined;
}

export interface VideoDraftSavedResponse {
  id: string;
  fileIdentifier: string;
  thumbnailIdentifier: string;
  expiresAt?: string | undefined;
}

export interface CheckUploadedVideoResponse {
  id: string;
  uploaded: boolean;
}

export interface VideoVisibilityChangedResponse {
  response: string;
  videoId: string;
  visibility: string;
}

export interface VideoUpdatedResponse {
  response: string;
  videoId: string;
}

export interface Empty {}

export const VIDEO_PACKAGE_NAME = 'Video';

export interface VideoServiceClient {
  saveDraft(request: VideoSaveDraftDto): Observable<VideoDraftSavedResponse>;

  checkUploadedVideo(request: CheckUploadedVideoDto): Observable<CheckUploadedVideoResponse>;

  update(request: VideoUpdateDto): Observable<VideoUpdatedResponse>;
}

export interface VideoServiceController {
  saveDraft(
    request: VideoSaveDraftDto,
  ):
    | Promise<VideoDraftSavedResponse>
    | Observable<VideoDraftSavedResponse>
    | VideoDraftSavedResponse;

  checkUploadedVideo(
    request: CheckUploadedVideoDto,
  ):
    | Promise<CheckUploadedVideoResponse>
    | Observable<CheckUploadedVideoResponse>
    | CheckUploadedVideoResponse;

  update(
    request: VideoUpdateDto,
  ): Promise<VideoUpdatedResponse> | Observable<VideoUpdatedResponse> | VideoUpdatedResponse;
}

export function VideoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['saveDraft', 'checkUploadedVideo', 'update'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('VideoService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('VideoService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VIDEO_SERVICE_NAME = 'VideoService';
