// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: views.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'Views';

export interface ViewsVideoDto {
  userId: string;
  videoId: string;
}

export interface ViewsVideoResponse {
  response: string;
}

export const VIEWS_PACKAGE_NAME = 'Views';

export interface ViewsServiceClient {
  viewVideo(request: ViewsVideoDto): Observable<ViewsVideoResponse>;
}

export interface ViewsServiceController {
  viewVideo(
    request: ViewsVideoDto,
  ): Promise<ViewsVideoResponse> | Observable<ViewsVideoResponse> | ViewsVideoResponse;
}

export function ViewsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['viewVideo'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ViewsService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ViewsService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VIEWS_SERVICE_NAME = 'ViewsService';
