export enum CACHE_EXCEPTION {
  CACHE_CONNECTION_EXCEPTION = 'CACHE_CONNECTION_EXCEPTION',
  CACHE_READ_EXCEPTION = 'CACHE_READ_EXCEPTION',
  CACHE_WRITE_EXCEPTION = 'CACHE_WRITE_EXCEPTION',
  CACHE_TIMEOUT_EXCEPTION = 'CACHE_TIMEOUT_EXCEPTION',
  CACHE_UNKNOWN_EXCEPTION = 'CACHE_UNKNOWN_EXCEPTION',
}
