export enum EVENT_BUS_EXCEPTION {
  EVENT_BUS_CONNECTION_EXCEPTION = 'EVENT_BUS_CONNECTION_EXCEPTION',
  EVENT_BUS_TIMEOUT_EXCEPTION = 'EVENT_BUS_TIMEOUT_EXCEPTION',
  EVENT_BUS_UNKNOWN_EXCEPTION = 'EVENT_BUS_UNKNOWN_EXCEPTION',
}
