// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.3
// source: query.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "Query";

export interface GetUserProfileFromIdDto {
  userId: string;
}

export interface GetUserProfileFromAuthIdDto {
  userAuthId: string;
}

export interface UserProfileMessage {
  userId: string;
  email: string;
  userAuthId: string;
  userName: string;
  avatar: string;
  handle: string;
  hasChannel: boolean;
  phoneNumber?: string | undefined;
  isPhoneNumberVerified?: boolean | undefined;
  dob?: string | undefined;
}

export interface GetUserProfileResponse {
  found: boolean;
  user?: UserProfileMessage | undefined;
}

export const QUERY_PACKAGE_NAME = "Query";

export interface QueryServiceClient {
  getUserProfileFromId(request: GetUserProfileFromIdDto): Observable<GetUserProfileResponse>;

  getUserProfileFromAuthId(request: GetUserProfileFromAuthIdDto): Observable<GetUserProfileResponse>;
}

export interface QueryServiceController {
  getUserProfileFromId(
    request: GetUserProfileFromIdDto,
  ): Promise<GetUserProfileResponse> | Observable<GetUserProfileResponse> | GetUserProfileResponse;

  getUserProfileFromAuthId(
    request: GetUserProfileFromAuthIdDto,
  ): Promise<GetUserProfileResponse> | Observable<GetUserProfileResponse> | GetUserProfileResponse;
}

export function QueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserProfileFromId", "getUserProfileFromAuthId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const QUERY_SERVICE_NAME = "QueryService";
