syntax = "proto3";

package Video;

enum VideoState {
  TRANSPORT_DRAFT = 0;
  TRANSPORT_PENDING_UPLOAD = 1;
  TRANSPORT_UPLOADED = 2;
  TRANSPORT_PROCESSING = 3;
  TRANSPORT_TRANSCODING = 4;
  TRANSPORT_READY_TO_PUBLISH = 5;
  TRANSPORT_PUBLISHED = 6;
  TRANSPORT_FAILED = 7;
}

enum VideoVisibilityState {
  TRANSPORT_PRIVATE = 0;
  TRANSPORT_PUBLIC = 1;
  TRANSPORT_UNLISTED = 2;
}

enum VideoTransportSortOption {
  TRANSPORT_NEWEST = 0;
  TRANSPORT_OLDEST = 1;
  TRANSPORT_POPULAR = 2;
}

message GetPresignedUrlDto {
  optional string fileName = 1;
  string userId = 2;
}

message VideoSaveDraftDto {
  string userId = 1;
  string channelId = 2;
  string title = 3;
  repeated string categories = 4;
  optional string description = 5;
}

message CheckUploadedVideoDto {
  string id = 1;
}

message VideoUpdateDto {
  string id = 1;
  optional string title = 2;
  optional string fileIdentifier = 3;
  optional string thumbnailIdentifier = 4;
  repeated string categories = 5;
  optional string description = 6;
  optional VideoVisibilityState videoVisibilityState = 7;
}

message VideoDraftSavedResponse {
  string id = 1;
  string fileIdentifier = 2;
  string thumbnailIdentifier = 3;
  optional string expiresAt = 4;
}

message CheckUploadedVideoResponse {
  string id = 1;
  bool uploaded = 2;
}

message VideoVisibilityChangedResponse {
  string response = 1;
  string videoId = 2;
  string visibility = 3;
}

message VideoUpdatedResponse {
  string response = 1;
  string videoId = 2;
}

message Empty {}

service VideoService {
  rpc saveDraft(VideoSaveDraftDto) returns (VideoDraftSavedResponse) {}
  rpc checkUploadedVideo(CheckUploadedVideoDto) returns (CheckUploadedVideoResponse) {}
  rpc update(VideoUpdateDto) returns (VideoUpdatedResponse) {}
}