syntax = "proto3";

package Video;

enum VideoState {
  TRANSPORT_DRAFT = 0;
  TRANSPORT_UPLOADED = 1;
  TRANSPORT_PROCESSING = 2;
  TRANSPORT_READY_TO_PUBLISH = 3;
  TRANSPORT_PUBLISHED = 4;
  TRANSPORT_FAILED = 5;
}

enum VideoVisibilityState {
  TRANSPORT_PRIVATE = 0;
  TRANSPORT_PUBLIC = 1;
  TRANSPORT_UNLISTED = 2;
}

message SaveVideoDraftDto {
  string userId = 1;
  string channelId = 2;
  string title = 3;
  repeated string categories = 4;
  optional string description = 5;
}

message VerifyVideoUploadedDto {
  string id = 1;
}

message CheckUploadedVideoDto {
  string id = 1;
}

message UpdateVideoDto {
  string id = 1;
  optional string title = 2;
  repeated string categories = 3;
  optional string description = 4;
  optional VideoVisibilityState videoVisibilityState = 5;
}

message VideoDraftSavedResponse {
  string id = 1;
  string fileIdentifier = 2;
  string thumbnailIdentifier = 3;
  optional string expiresAt = 4;
}

message VideoUploadedVerifiedResponse {
  string id = 1;
  bool uploaded = 2;
}

message VideoVisibilityChangedResponse {
  string response = 1;
  string videoId = 2;
  string visibility = 3;
}

message VideoUpdatedResponse {
  string response = 1;
  string videoId = 2;
}

message Empty {}

service VideoService {
  rpc saveDraft(SaveVideoDraftDto) returns (VideoDraftSavedResponse) {}
  rpc checkUploadedVideo(CheckUploadedVideoDto) returns (VideoUploadedVerifiedResponse) {}
  rpc update(UpdateVideoDto) returns (VideoUpdatedResponse) {}
}