export enum USER_INTEGRATION_EVENTS {
  USER_LANGUAGE_CHANGED_INTEGRATION_EVENT = 'USER_LANGUAGE_CHANGED_INTEGRATION_EVENT',
  USER_NOTIFICATION_CHANGED_INTEGRATION_EVENT = 'USER_NOTIFICATION_CHANGED_INTEGRATION_EVENT',
  USER_ONBOARDED_INTEGRATION_EVENT = 'USER_ONBOARDED_INTEGRATION_EVENT',
  USER_PHONE_NUMBER_UPDATED_INTEGRATION_EVENT = 'USER_PHONE_NUMBER_UPDATED_INTEGRATION_EVENT',
  USER_THEME_CHANGED_INTEGRATION_EVENT = 'USER_THEME_CHANGED_INTEGRATION_EVENT',
  USER_PROFILE_UPDATED_INTEGRATION_EVENT = 'USER_PROFILE_UPDATED_INTEGRATION_EVENT',
}
